datasource:
  url: jdbc:mysql://localhost:3306/teste?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: root
  password: root 
h2:
  console:
    enabled: true
    path: /h2-mscliente
jpa:
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQL8Dialect

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/teste?createDatabaseIfNotExist=true&serverTimezone=UTC
#    username: root
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#          ddl-auto: update
#    show-sql: true
#  flyway:
#    locations: classpath:db/migrations, classpath:db/testdata  
    
  server:
    port: 0    

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@ms-eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  

#Configuração actuator    
management:
  endpoints:
    web:
      exposure:
        include: '*'

# Configurando arquivo de log        
logging:
  file:
#nome e logal do arquivo  
    name: ./logs/log-file.log    
      
