#Banco de dados
  datasource:
    url: jdbc:h2:file:./data/ms-vendas 
    username: root
    password: root 
  h2:
    console:
      enabled: true
      path: /h2-mscliente
  jpa:
    hibernate:
      ddl-auto: update
